services:
  labra-dashboard:
    container_name: labra-dashboard
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "4080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./analytics-data:/app/data

  analytics-api:
    container_name: analytics-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./analytics-data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production